services:
  server:
    build:
      context: .
    ports:
      - 8001:8001
    volumes:
      - .:/app
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    develop:
      watch:
        - action: rebuild
          path: .
  front:
    build:
      context: .
    command:
      [
        "streamlit",
        "run",
        "app/front.py",
        "--server.port=8501",
        "--server.address=0.0.0.0",
        "--server.headless=true",
      ]
    environment:
      - API_BASE_URL=http://server:8001
    ports:
      - 8501:8501
    volumes:
      - .:/app
    depends_on:
      - server
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
